name: Laravel Security Check

on: [push]
   
jobs:
  laravel-security-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Install Laravel Shift Security Checker
      - name: Install Laravel Shift Security Checker
        run: composer require laravel-shift/security-checker

      # Run Security Check
      - name: Run Laravel Security Check
        run: php artisan security:check
